repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: "bash -c 'source activate quickstart && black'"
        require_serial: true
        types: [python]