version: '3.7'
services:

  dev:
    build: 
      context: .
      target: dev
    image: dev_image
    volumes:
      - .:/home/root/project/
    #  - ~/.ssh:/home/root/.ssh-localhost:ro
    command: /bin/bash
    tty: true

  prod:
    build: 
      context: .
      target: prod
    image: prod_image
